---

- name: Install nginx (APT)
  ansible.builtin.apt:
    name: nginx-{{ nginx_flavor }}
  notify:
    - Restart nginx

- name: Disable default vhost
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify:
    - Reload nginx
