---

- name: Include pkgin-specific variables
  ansible.builtin.include_vars: pkgin.yml

- name: Install nginx
  community.general.pkgin:
    name: nginx
  notify:
    - Restart nginx

- name: Set permissions on temporary directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ nginx_conf_user | default('www') }}"
    group: "{{ nginx_conf_group | default('www') }}"
    mode: "0700"
  with_items:
    - /var/db/nginx

- name: Template nginx config file
  ansible.builtin.template:
    src: pkgin-nginx.conf.j2
    dest: "{{ nginx_conf_file }}"
    backup: true
    mode: "0644"
  notify:
    - Restart nginx

- name: Create local config directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  with_items:
    - "{{ nginx_conf_dir }}/conf.d"
    - "{{ nginx_conf_dir }}/sites-available"
    - "{{ nginx_conf_dir }}/sites-enabled"
  notify:
    - Reload nginx

- name: Create config including virtual hosts
  ansible.builtin.copy:
    dest: "{{ nginx_conf_dir }}/conf.d/sites-enabled.conf"
    content: |
      ## This file is maintained by Ansible - CHANGES WILL BE OVERWRITTEN
      include {{ nginx_conf_dir }}/sites-enabled/*;
    mode: "0644"
  notify:
    - Reload nginx
