---

- name: SELinux task block for certbot_well_known_root
  when: certbot_well_known_root is defined
  block:

    - name: Ensure that certbot_well_known_root exists
      ansible.builtin.file:
        path: "{{ certbot_well_known_root }}"
        state: directory
        mode: "0755"

    - name: "Allow nginx httpd_sys_content_t to access the well-known root"
      community.general.sefcontext:
        target: '{{ certbot_well_known_root }}(/.*)?'
        setype: httpd_sys_content_t
        state: present
      register: __nginx_update_fcontexts

    - name: Apply new SELinux file context to filesystem  # noqa: no-changed-when no-handler
      ansible.builtin.command: "restorecon -rv {{ certbot_well_known_root }}"
      when: __nginx_update_fcontexts.changed

- name: "Allow connecting to localhost"
  ansible.posix.seboolean:
    name: httpd_can_network_connect
    state: true
    persistent: true
  when: nginx_selinux_allow_local_connections
