---

- name: Create SSL directory
  ansible.builtin.file:
    path: "{{ nginx_ssl_conf_dir }}"
    state: directory
    mode: "0755"
    owner: root
    group: root

- name: Install SSL certificate
  ansible.builtin.copy:
    src: "{{ nginx_ssl_src_dir }}/{{ nginx_conf_ssl_certificate }}"
    dest: "{{ nginx_ssl_conf_dir }}/{{ nginx_conf_ssl_certificate | basename }}"
    mode: "0644"
    owner: root
    group: root
  when: nginx_conf_ssl_certificate.0 != '/'

- name: Install SSL private key
  ansible.builtin.copy:
    src: "{{ nginx_ssl_src_dir }}/{{ nginx_conf_ssl_certificate_key }}"
    dest: "{{ nginx_ssl_conf_dir }}/{{ nginx_conf_ssl_certificate_key | basename }}"
    mode: "{{ nginx_conf_ssl_certificate_key_mode | default('0400') }}"
    owner: root
    group: root
  when: nginx_conf_ssl_certificate_key.0 != '/'

- name: Install trusted certificates for OCSP with stapling
  ansible.builtin.copy:
    src: "{{ nginx_ssl_src_dir }}/{{ nginx_conf_ssl_trusted_certificate }}"
    dest: "{{ nginx_ssl_conf_dir }}/{{ nginx_conf_ssl_trusted_certificate | basename }}"
    mode: "0644"
    owner: root
    group: root
  when: nginx_conf_ssl_trusted_certificate is defined and nginx_conf_ssl_trusted_certificate.0 != '/'

- name: Make SSL certificate/key paths absolute for config
  ansible.builtin.set_fact:
    nginx_conf_ssl_certificate: >-
      {{ nginx_ssl_conf_dir ~ '/' ~ nginx_conf_ssl_certificate if nginx_conf_ssl_certificate.0 != '/' else nginx_conf_ssl_certificate }}
    nginx_conf_ssl_certificate_key: >-
      {{ nginx_ssl_conf_dir ~ '/' ~ nginx_conf_ssl_certificate_key if nginx_conf_ssl_certificate_key.0 != '/' else nginx_conf_ssl_certificate_key }}

- name: Make SSL trusted certificate path absolute for config
  ansible.builtin.set_fact:   
    nginx_conf_ssl_trusted_certificate: >-
      {{ nginx_ssl_conf_dir ~ '/' ~ nginx_conf_ssl_trusted_certificate if nginx_conf_ssl_trusted_certificate.0 != '/' else nginx_conf_ssl_trusted_certificate }}
  when: nginx_conf_ssl_trusted_certificate is defined

- name: Include common SSL tasks
  ansible.builtin.import_tasks: ssl-common.yml
