---

# Some versions of Debian set this in nginx.conf, and unlike other vars such as ssl_protocols, this does not override
# other entires.
- name: Disable ssl_prefer_server_ciphers in nginx.conf if set
  ansible.builtin.lineinfile:
    name: "{{ nginx_conf_file }}"
    regexp: '^(\s*ssl_prefer_server_ciphers\s.*)'
    backrefs: true
    line: '#\1 # commented by Ansible'
    backup: true
  notify:
    - Reload nginx

- name: Configure server-wide SSL
  ansible.builtin.template:
    src: ssl.conf.j2
    dest: "{{ nginx_conf_dir }}/conf.d/ssl.conf"
    mode: "0444"
    backup: true
  register: __nginx_ssl_config_results
  notify:
    - Restart nginx

- name: Ensure nginx SSL directory exists
  ansible.builtin.file:
    path: "{{ nginx_ssl_conf_dir }}"
    state: directory
    mode: "0755"

- name: Generate strong Diffie-Hellman group
  ansible.builtin.command: openssl dhparam -out {{ nginx_ssl_conf_dir }}/dhparams.pem 2048
  args:
    creates: "{{ nginx_conf_ssl_dhparam }}"
  when: nginx_conf_ssl_dhparam
