---

- name: Flush handlers before running SSL role
  ansible.builtin.meta: flush_handlers

- name: Include SSL role
  ansible.builtin.include_role:
    name: "{{ nginx_ssl_role }}"

- name: Include common SSL tasks
  ansible.builtin.import_tasks: ssl-common.yml
