---

# This is almost an exact copy of server.yml, but is necessary because the register value is not templateable but must
# be unique for restore on config test failure to work.

- name: Install SSL vhost configs
  ansible.builtin.template:
    src: "{{ nginx_server_src_dir }}/{{ item }}.j2"
    dest: "{{ nginx_conf_dir }}/sites-available/{{ item | basename }}"
    mode: "0444"
    backup: true
  loop: "{{ nginx_ssl_servers }}"
  register: __nginx_ssl_server_config_results
  notify:
    - Reload nginx

- name: Enable SSL vhosts
  ansible.builtin.file:
    src: "{{ nginx_conf_dir }}/sites-available/{{ item | basename }}"
    dest: "{{ nginx_conf_dir }}/sites-enabled/{{ item | basename }}"
    state: link
  loop: "{{ nginx_ssl_servers }}"
  register: __nginx_ssl_server_link_results
  notify:
    - Reload nginx
  # Ansible will exit due to src file missing.
  when: not ansible_check_mode
